# Ruff configuration for SignalDrift
# See https://docs.astral.sh/ruff/configuration/ for more options

[lint]
# Enable specific linting rules
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "PL",   # Pylint
]

# Ignore specific rules that may be too strict for this codebase
ignore = [
    "E501",   # Line too long (let formatter handle this)
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
]

# Allow autofix for specific rule categories
fixable = ["ALL"]
unfixable = []

# Exclude specific files and directories
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "venv",
    ".venv",
    "notebooks",  # Exclude notebooks as they have different formatting needs
]

[format]
# Use double quotes for strings
quote-style = "double"

# Use 4 spaces for indentation
indent-style = "space"

# Skip formatting for notebooks
exclude = ["notebooks/**/*.py"]

[lint.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]

# Allow print statements in main.py and test files
"src/main.py" = ["T201"]
"src/tests/**/*.py" = ["T201"]

[lint.isort]
# Configure import sorting to match project structure
known-first-party = ["calculators", "daos", "models", "scrapers", "services", "strategies", "utils"]