
ssc.cookieSpace=(function(){var date=new Date(),expr,timestamp=new Date().getTime(),existingCookies,existingCookiesArray,cookie,cname="bfsd=",cookieIsSet,minutes,path,bfSType,bfDomain,getCookie,hostname=document.location.hostname,stringTrim;path="/";bfDomain=hostname.startsWith("sky")?hostname:hostname.match(/\.(.*)$/)[1];date.setTime(date.getTime()+(365*24*60*60*1000));expr="; expires="+date.toGMTString();existingCookies=document.cookie;existingCookiesArray=existingCookies.split(";");stringTrim=function(str){return str.replace(/^\s+|\s+$/g,'');}
getCookie=function(){var cIsSet,sCookie,sType,timeStamp,TsArr,sessionTypeArr,cookieArr;for(var i=0;i<existingCookiesArray.length;i++){cookie=stringTrim(existingCookiesArray[i]);if(cookie.indexOf(cname)==0){cIsSet=true;sCookie=cookie.substring(cname.length);cookieArr=sCookie.split("|");TsArr=cookieArr[0];sessionTypeArr=cookieArr[1];timeStamp=stringTrim(TsArr).split("=")[1];sType=sessionTypeArr.split("=")[1];}}
return{cookieIsSet:cIsSet,sessionCookie:sCookie,sessionType:sType,TS:timeStamp}};cookieIsSet=getCookie().cookieIsSet;if(cookieIsSet){if(getCookie().sessionType==="p"){minutes=Math.round((timestamp-getCookie().TS)/(60*1000));if(minutes>24*60){document.cookie=cname+"ts="+timestamp+"|st=rp; expires="+expr+"; path="+path+"; domain="+bfDomain;}}}else{cookieIsSet=true;document.cookie=cname+"ts="+timestamp+"|st=p; expires="+expr+"; path="+path+"; domain="+bfDomain;}
if(ssc.isLoggedIn){if(!cookieIsSet||(cookieIsSet&&getCookie().sessionType!=="reg")){cookieIsSet=true;document.cookie=cname+"ts="+timestamp+"|st=reg; expires="+expr+"; path="+path+"; domain="+bfDomain;}}
switch(getCookie().sessionType){case"p":bfSType="New prospect";if(minutes>24*60){bfSType="Returning Prospect";}
break;case"rp":bfSType="Returning Prospect";break;case"reg":bfSType="Returning Registered";break;default:if(ssc.isLoggedIn){bfSType="Returning Registered";}else{bfSType="New prospect";}
break;}return{bfSessionType:bfSType}})();ssc.isLoggedIn=undefined;ssc.imediateScript("ssc-header-container");ssc.initGA=function(){ga('set','dimension49',ssc.cookieSpace.bfSessionType);};
ssc.prospectCookie = (ssc.cookieSpace.bfSessionType === "New prospect" || ssc.cookieSpace.bfSessionType === "Returning Prospect");
