name: Test Suite

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Debug environment
      run: |
        echo "Python version:"
        python --version
        echo "Pytest version:"
        pytest --version
        echo "Working directory:"
        pwd
        echo "Python path:"
        python -c "import sys; print('\n'.join(sys.path))"
        echo "Directory contents:"
        ls -la
        echo "Source directory contents:"
        ls -la src/
        
    - name: Run tests with pytest
      run: |
        PYTHONPATH=src pytest src/
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          .coverage
          htmlcov/
        retention-days: 30